---
name: POE-Component-IRC-Plugin-CPAN-Info
version: 0.01
author:
  - 'Zoffix Znet <zoffix@cpan.org>'
abstract: |-
  PoCo::IRC plugin for accessing
  information about CPAN modules, distributions and authors.
license: perl
resources:
  license: http://dev.perl.org/licenses/
requires:
  Carp: 1.04
  POE: 0.9999
  POE::Component::CPAN::SQLite::Info: 0.06
  POE::Component::IRC::Plugin: 0.09
build_requires:
  Test::More: 0
provides:
  POE::Component::IRC::Plugin::CPAN::Info:
    file: lib/POE/Component/IRC/Plugin/CPAN/Info.pm
    version: 0.01
generated_by: Module::Build version 0.2808
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.2.html
  version: 1.2
